#+TITLE: T3PRF: Three Pass Regression Filter for R
#+AUTHOR: Mohamed Ishmael Diwan Belghazi
#+EMAIL: ishmael.belghazi@gmail.com
 [[https://travis-ci.org/IshmaelBelghazi/T3PRF][https://travis-ci.org/IshmaelBelghazi/T3PRF.svg?branch=master]]
 [[https://coveralls.io/repos/IshmaelBelghazi/T3PRF/badge.svg?branch=master]]
* The Three Pass Regression Filter
Consider a linear regression model with a large number of predictors.
If the number of predictors is close to the number of observations or greater then the OLS estimate is poorly behaved or
inexistent. A typical solution would be to assume a latent factor
structure. That is to say, one would assume that the predictors are explained
by a limited number of latent factors. \\

Principal component regression (PCR), where the factors are some of the principal
components of the predictors is an example of such an approach. \\

In context of forecasting a criticism of PCR would that the extracted factors
are not chosen with respect to target. The factors (principal components), are
selected to minimize the reconstruction error but correlation with the target
is not considered.

By assuming that the same latent factors explain both the target and the predictors, The Three Pass Regression
Filter(T3PRF) selects the components in such a way to minimize the
reconstruction error while at same time maximizing the correlation with the
target.

* References:
Kelly, Bryan T. and Pruitt, Seth, The Three-Pass Regression Filter: A New Approach to Forecasting Using Many Predictors (May 2014). Fama-Miller Working Paper; Chicago Booth Research Paper No. 11-19. Available at SSRN: http://ssrn.com/abstract=1868703 or http://dx.doi.org/10.2139/ssrn.1868703

* TODOS
**** TODO Complete Documentation
**** TODO Add asymptotics
**** TODO Add examples
**** TODO Add vignette
**** DONE Improve testing
**** DONE Improve handling of missing values
**** CANCELLED Move from RcppEigen to native .Call with LAPACK
**** TODO Add GPU support especially for rolling and recursive forecasts
