#+TITLE: T3PRF - Three Pass Regression Filter for R
#+AUTHOR: Mohamed Ishmael Diwan Belghazi
#+EMAIL: ishmael.belghazi@gmail.com

* The Three Pass Regression Filter
Consider the following regression model, $\mathbf{y} = \mathbf{X} \beta +
\eta$ \\

Where, $\mathbf{y}$ is $T \times 1$ vector of targets and $\mathbf{X}$ is a $T \times N$ matrix of predictors. \\

If $N$ is close to $T$, or $N > T$ then the OLS estimate is poorly behaved or
inexistent. A typical solution would be to assume a latent factor
structure. That is to day, one would assume $\mathbf{X}$ is generated by a
limited number factors $\mathbf{F}$ : $X = \mathbf{F} \Phi^{'} + \epsilon$ \\

Principal component regression (PCR), where the factors are some of the principal
components of $\mathbf{X}$ is an example of such an approach. \\

In context of forecasting a criticism of PCR would that the extracted factors
are not chosen with respect to target. The factors (principal components), are
selected to minimize the reconstruction error but correlation with the target
is not considered. \\

By assuming the following latent factor structure, The Three Pass Regression
Filter(T3PRF) selects the components in such a way to minimize the
reconstruction error while at same time maximizing the correlation with the
target: \\

$\mathbf{y} = \mathbf{F} \beta + \eta$ and $X = \mathbf{F} \Phi^{'} + \epsilon$

* References:
Kelly, Bryan T. and Pruitt, Seth, The Three-Pass Regression Filter: A New Approach to Forecasting Using Many Predictors (May 2014). Fama-Miller Working Paper; Chicago Booth Research Paper No. 11-19. Available at SSRN: http://ssrn.com/abstract=1868703 or http://dx.doi.org/10.2139/ssrn.1868703

* TODOS
** TODO Improve testing
** TODO Improve handling of missing values
** TODO Move from RcppEigen to native .Call with LAPACK
** TODO Add GPU support for rolling and recursive forecasts
